# 服务端口
server:
  port: 8001
  # 服务名
spring:
  application:
    name: guli-teacher
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.128:33306/guli_edu?characterEncoding=utf-8&useSSL=false
    username: root
    password: qiu123.
  #mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
